#!/usr/bin/env bash
# 初始化 git 仓库：init + 分支 main + 确保 .gitignore + 约定式首提交。
# 用法： bash scripts/git_init.sh [项目目录] [可选远程地址]
set -euo pipefail

DIR="${1:-.}"
REMOTE="${2:-}"
cd "$DIR"

[ -d .git ] || git init -q

# 确保在 main 分支
if ! git symbolic-ref --quiet HEAD 2>/dev/null | grep -q "refs/heads/main"; then
  git symbolic-ref HEAD refs/heads/main 2>/dev/null || git checkout -q -b main 2>/dev/null || true
fi

# 若无 .gitignore，写入标准忽略
if [ ! -f .gitignore ]; then
  cat > .gitignore <<'EOF'
config.toml
.env
account/
accounts/
.venv/
__pycache__/
*.pyc
.pytest_cache/
.ruff_cache/
.mypy_cache/
*.egg-info/
dist/
build/
/tmp/
EOF
fi

git add -A
if git diff --cached --quiet; then
  echo "无变更可提交"
else
  git commit -q -m "feat: initial $(basename "$PWD") scaffold (generated by 2api-skill)"
  echo "已提交: $(git rev-parse --short HEAD)"
fi

[ -z "$REMOTE" ] || { git remote remove origin 2>/dev/null || true; git remote add origin "$REMOTE"; }

BRANCH="$(git branch --show-current 2>/dev/null || echo main)"
echo "git 初始化完成（分支: $BRANCH）"
